#!/usr/bin/env python3
import os
import platform
import sys
import urllib.request
import zipfile

PB_VER = "0.22.12"
PB_BASE_URL = "https://github.com/pocketbase/pocketbase/releases/download"


def main():
    cpu = platform.processor()
    arch = {"x86_64": "amd64", "arm": "arm64"}.get(cpu, cpu)
    plat = {"win32": "windows"}.get(sys.platform, sys.platform)
    zip_fn = f"pocketbase_{PB_VER}_{plat}_{arch}.zip"
    url = f"{PB_BASE_URL}/v{PB_VER}/{zip_fn}"

    is_new_zip_file = not os.path.exists(zip_fn)
    if is_new_zip_file:
        print(f"Downloading PocketBase from: {url}")
        urllib.request.urlretrieve(url, zip_fn)

    pb_exe = f"pocketbase{'.exe' if sys.platform == 'win32' else ''}"
    if is_new_zip_file or not os.path.exists(pb_exe):
        print(f"Unzipping {zip_fn}")
        with zipfile.ZipFile(zip_fn, "r") as zipf:
            zipf.extractall()
            if not pb_exe.endswith(".exe"):
                os.chmod(pb_exe, 0o777 & ~os.umask(0o022))


if __name__ == "__main__":
    main()
