#!/usr/bin/env python3
import os
import platform
import sys
import urllib.request
import zipfile

PB_VER = "0.22.9"
PB_BASE_URL = "https://github.com/pocketbase/pocketbase/releases/download"


def main():
    url = get_pocketbase_url()
    download_and_unzip(url)


def get_pocketbase_url():
    cpu = platform.processor()
    arch = {"x86_64": "amd64", "arm": "arm64"}.get(cpu, cpu)
    plat = {"win32": "windows"}.get(sys.platform, sys.platform)
    return f"{PB_BASE_URL}/v{PB_VER}/pocketbase_{PB_VER}_{plat}_{arch}.zip"


def download_and_unzip(url):
    zip_filename = url.rsplit("/", 1)[-1]
    is_new_zip_file = not os.path.exists(zip_filename)
    if is_new_zip_file:
        print(f"Downloading PocketBase from: {url}")
        urllib.request.urlretrieve(url, zip_filename)
    exe_suffix = ".exe" if sys.platform == "win32" else ""
    pb_exe = f"pocketbase{exe_suffix}"
    if is_new_zip_file or not os.path.exists(pb_exe):
        print(f"Unzipping {zip_filename}")
        with zipfile.ZipFile(zip_filename, "r") as zipf:
            zipf.extractall()
            if not pb_exe.endswith(".exe"):
                os.chmod(pb_exe, 0o777 & ~os.umask(0o022))


if __name__ == "__main__":
    main()
